// <auto-generated />
using System;
using EducationalPortal.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationalPortal.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220315121757_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.EducationalYearModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EducationalYears");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("HomeworkId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HomeworkId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.GradeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.HomeworkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mark")
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewResult")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SubjectPostId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectPostId");

                    b.ToTable("Homeworks");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SettingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SubjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("EducationalYearId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EducationalYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SubjectPostModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SubjectPosts");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradeModelSubjectModel", b =>
                {
                    b.Property<Guid>("GradesHaveAccessReadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectsHaveAccessReadId")
                        .HasColumnType("char(36)");

                    b.HasKey("GradesHaveAccessReadId", "SubjectsHaveAccessReadId");

                    b.HasIndex("SubjectsHaveAccessReadId");

                    b.ToTable("GradeModelSubjectModel");
                });

            modelBuilder.Entity("SubjectModelUserModel", b =>
                {
                    b.Property<Guid>("SubjectHaveAccessCreatePostsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeachersHaveAccessCreatePostsId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubjectHaveAccessCreatePostsId", "TeachersHaveAccessCreatePostsId");

                    b.HasIndex("TeachersHaveAccessCreatePostsId");

                    b.ToTable("SubjectModelUserModel");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.FileModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.HomeworkModel", "Homework")
                        .WithMany("Files")
                        .HasForeignKey("HomeworkId");

                    b.Navigation("Homework");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.HomeworkModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.UserModel", "Student")
                        .WithMany("Homeworks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationalPortal.Server.Database.Models.SubjectPostModel", "SubjectPost")
                        .WithMany("Homeworks")
                        .HasForeignKey("SubjectPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("SubjectPost");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SubjectModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.EducationalYearModel", "EducationalYear")
                        .WithMany("Subjects")
                        .HasForeignKey("EducationalYearId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationalPortal.Server.Database.Models.UserModel", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("EducationalYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SubjectPostModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.SubjectModel", "Subject")
                        .WithMany("Posts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EducationalPortal.Server.Database.Models.UserModel", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.UserModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.GradeModel", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("GradeModelSubjectModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.GradeModel", null)
                        .WithMany()
                        .HasForeignKey("GradesHaveAccessReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationalPortal.Server.Database.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectsHaveAccessReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubjectModelUserModel", b =>
                {
                    b.HasOne("EducationalPortal.Server.Database.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectHaveAccessCreatePostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationalPortal.Server.Database.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("TeachersHaveAccessCreatePostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.EducationalYearModel", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.GradeModel", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.HomeworkModel", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SubjectModel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.SubjectPostModel", b =>
                {
                    b.Navigation("Homeworks");
                });

            modelBuilder.Entity("EducationalPortal.Server.Database.Models.UserModel", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
