// <auto-generated />
using System;
using EducationalPortal.Portgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducationalPortal.Portgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationalPortal.Business.Models.BackupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.EducationalYearModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EducationalYears");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HomeworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("HomeworkId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.GradeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.HomeworkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mark")
                        .HasColumnType("text");

                    b.Property<string>("ReviewResult")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectPostId");

                    b.ToTable("Homeworks");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SettingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SubjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EducationalYearId")
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EducationalYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SubjectPostModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SubjectPosts");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradeModelSubjectModel", b =>
                {
                    b.Property<Guid>("GradesHaveAccessReadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectsHaveAccessReadId")
                        .HasColumnType("uuid");

                    b.HasKey("GradesHaveAccessReadId", "SubjectsHaveAccessReadId");

                    b.HasIndex("SubjectsHaveAccessReadId");

                    b.ToTable("GradeModelSubjectModel");
                });

            modelBuilder.Entity("SubjectModelUserModel", b =>
                {
                    b.Property<Guid>("SubjectHaveAccessCreatePostsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeachersHaveAccessCreatePostsId")
                        .HasColumnType("uuid");

                    b.HasKey("SubjectHaveAccessCreatePostsId", "TeachersHaveAccessCreatePostsId");

                    b.HasIndex("TeachersHaveAccessCreatePostsId");

                    b.ToTable("SubjectModelUserModel");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.BackupModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.FileModel", "File")
                        .WithOne("Backup")
                        .HasForeignKey("EducationalPortal.Business.Models.BackupModel", "FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("File");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.FileModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.UserModel", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("EducationalPortal.Business.Models.HomeworkModel", "Homework")
                        .WithMany("Files")
                        .HasForeignKey("HomeworkId");

                    b.Navigation("Creator");

                    b.Navigation("Homework");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.HomeworkModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.UserModel", "Student")
                        .WithMany("Homeworks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationalPortal.Business.Models.SubjectPostModel", "SubjectPost")
                        .WithMany("Homeworks")
                        .HasForeignKey("SubjectPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("SubjectPost");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SubjectModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.EducationalYearModel", "EducationalYear")
                        .WithMany("Subjects")
                        .HasForeignKey("EducationalYearId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationalPortal.Business.Models.UserModel", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("EducationalYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SubjectPostModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.SubjectModel", "Subject")
                        .WithMany("Posts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EducationalPortal.Business.Models.UserModel", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.UserModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.GradeModel", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("GradeModelSubjectModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.GradeModel", null)
                        .WithMany()
                        .HasForeignKey("GradesHaveAccessReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationalPortal.Business.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectsHaveAccessReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubjectModelUserModel", b =>
                {
                    b.HasOne("EducationalPortal.Business.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectHaveAccessCreatePostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationalPortal.Business.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("TeachersHaveAccessCreatePostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.EducationalYearModel", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.FileModel", b =>
                {
                    b.Navigation("Backup");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.GradeModel", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.HomeworkModel", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SubjectModel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.SubjectPostModel", b =>
                {
                    b.Navigation("Homeworks");
                });

            modelBuilder.Entity("EducationalPortal.Business.Models.UserModel", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
